# Exported from Render on 2024-11-04T01:57:46Z
services:
- type: web
  name: palmyra-ny-stake
  runtime: python
  repo: https://github.com/mikeasilva/palmyra-ny-stake
  plan: starter
  region: ohio
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
version: "1"
